export const SET_ROOT_SEED = "SET_ROOT_SEED";
export const SET_SUB_SEEDS = "SET_SUB_SEEDS";
export const SET_SHOP_DATA = "SET_SHOP_DATA";
export const SET_SHOP_DISPLAY = "SET_SHOP_DISPLAY";
export const SET_SHOP_OPTIONS = "SET_SHOP_OPTIONS";
export const RUN_SHOP_GENERATE = "RUN_SHOP_GENERATE";
export const RUN_CHARACTER_MAP_GENERATE = "RUN_CHARACTER_MAP_GENERATE";